parallel-jobs = 1
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "auto"
build-mode = "module"
excluded-patches = "custom-branding vanced-microg-support"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"
version = "auto"
build-mode = "module"
excluded-patches = "vanced-microg-support"

[Twitter]
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
version = "auto"
build-mode = "module"

[Twitch]
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
version = "auto"
build-mode = "module"

[Reddit]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
version = "auto"
build-mode = "module"

[Messenger]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"
version = "auto"
build-mode = "module"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
apkmirror-arch = "arm64-v8a"
version = "auto"
build-mode = "module"
