logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
version = "auto"
build-mode = "module"
excluded-patches = "'Vanced MicroG support' 'Custom branding'"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
apkmirror-arch = "arm64-v8a"
version = "auto"
build-mode = "module"
excluded-patches = "'Vanced MicroG support'"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Twitter]
version = "auto"
build-mode = "module"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[Twitch]
version = "auto"
build-mode = "module"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[Reddit]
version = "auto"
build-mode = "module"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Messenger]
apkmirror-arch = "arm64-v8a"
version = "auto"
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
apkmirror-arch = "arm64-v8a"
version = "auto"
build-mode = "module"
