enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "module"
excluded-patches = "'Vanced MicroG support' 'Custom branding'"
included-patches = ""
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" # fallback

[Music]
arch = "arm64-v8a"
build-mode = "module"
excluded-patches = "'Vanced MicroG support'"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[Twitter]
build-mode = "module"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[Twitch]
build-mode = "module"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[Reddit]
build-mode = "module"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Messenger]
arch = "arm64-v8a"
build-mode = "module"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"

